set(TRADE_CLI_SOURCES
    src/cli/main.cpp
    src/cli/args.cpp
    src/cli/shared.cpp
    src/cli/commands_data.cpp
    src/cli/commands_analysis.cpp
    src/cli/commands_sentiment.cpp
    src/cli/commands_report.cpp
)
